# Generated by Django 3.1.7 on 2021-03-05 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_blogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='blogs',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
        migrations.DeleteModel(
            name='FollowRelationship',
        ),
    ]
