# Generated by Django 3.1.7 on 2021-04-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='users/default/default_avatar.jpeg', upload_to='users/%Y/%m/%d/'),
        ),
    ]
