# Generated by Django 3.1.7 on 2021-03-05 00:52

from django.db import migrations, models

import blogs.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_auto_20210304_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(
                blank=True, upload_to=blogs.utils.get_post_image_dir_path),
        ),
    ]
