# Generated by Django 3.1.7 on 2021-04-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_auto_20210327_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='followrelationship',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
