# Generated by Django 3.1.7 on 2021-03-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taggeditem',
            old_name='tag',
            new_name='slug',
        ),
    ]
