# Generated by Django 3.1.7 on 2021-03-27 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tags', '0002_auto_20210327_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterIndexTogether(
            name='taggeditem',
            index_together={('content_type', 'object_id')},
        ),
        migrations.AddField(
            model_name='taggeditem',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tags.tag'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='taggeditem',
            unique_together={('content_type', 'object_id', 'tag')},
        ),
        migrations.RemoveField(
            model_name='taggeditem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='taggeditem',
            name='slug',
        ),
    ]
