# Generated by Django 3.1.7 on 2021-03-01 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='about',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='blog',
            name='last_name',
            field=models.CharField(default='Kowalski', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blogs.blog'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
