# Generated by Django 3.1.7 on 2021-03-01 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20210301_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='description',
            new_name='about',
        ),
    ]
