# Generated by Django 3.1.7 on 2021-03-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_auto_20210305_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blog',
        ),
    ]
