# Generated by Django 3.1.7 on 2021-03-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20210309_1238'),
        ('blogs', '0014_remove_post_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
