# Generated by Django 3.1.7 on 2021-03-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_auto_20210327_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='taggeditem',
            name='name',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taggeditem',
            name='tag',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='taggeditem',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='taggeditem',
            index_together=set(),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
