# Generated by Django 3.1.7 on 2021-03-27 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_auto_20210327_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taggeditem',
            old_name='tag',
            new_name='slug',
        ),
    ]
