# Generated by Django 3.1.7 on 2021-03-05 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_auto_20210305_0052'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_to_set', to='blogs.blog')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_from_set', to='account.profile')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='account.FollowRelationship', to='blogs.Blog'),
        ),
    ]
